import 'package:ege_helper/features/profile/profile.dart';
import 'package:ege_helper/ui/ui.dart';
import 'package:flutter/material.dart';

class ActivityProfileCard extends StatelessWidget {
  const ActivityProfileCard({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return BaseContainer(
      width: double.infinity,
      height: 210,
      margin: EdgeInsets.only(left: 15, right: 15).copyWith(top: 30),
      child: Wrap(
        children: [
          Container(
            width: 150,
            height: 20,
            margin: EdgeInsets.all(10),
            color: Colors.grey,
          ),
          Container(
              width: 280,
              height: 130,
              margin: EdgeInsets.all(10).copyWith(top: 15),
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(16),
              ),
              child: Container(
                margin: EdgeInsets.all(4),
                child: Wrap(
                  direction: Axis.vertical,
                  alignment: WrapAlignment.start,
                  crossAxisAlignment: WrapCrossAlignment.start,
                  children: [
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                    ActivitySquare(),
                  ],
                ),
              ))
        ],
      ),
    );
  }
}
